title: My Blogs
author: vicente-s
email: vicenteajr.soriano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Development and Skateboarding related content.

github_username:  vicente-s 
show_excerpts: true
theme: minima
